language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
#  - "pypy"
# command to install dependencies

addons:
  apt:
    packages:
    - dpkg-dev
    - build-essential
    - freeglut3
    - freeglut3-dev
    - libgstreamer-plugins-base0.10-dev
    - libgtk-3-dev
    - libjpeg-dev
    - libnotify-dev
    - libwebkitgtk-3.0-dev
    - libsdl1.2-dev
    - libsm-dev
    - libtiff-dev
    - libxtst-dev

env:
  - LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH

# command to install dependencies
install: 
  - sudo apt-get update
  - wget "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.1-cp27-cp27mu-linux_x86_64.whl"
  - pip install wxPython-4.0.1-cp27-cp27mu-linux_x86_64.whl
  - pip install .

# command to run tests
script:
  - echo $LD_LIBRARY_PATH
  - locate libstdc++
  - zbc